# baseURL = 'https://Elari39.github.io/'
baseURL = 'https://blog.miku831.fun/'
enableRobotsTXT = true
languageCode = 'zh-cn'
timeZone = "Asia/Shanghai"
title = 'Elari的博客'

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]
