baseURL = 'https://Elari39.github.io/'
enableRobotsTXT = true
languageCode = 'zh-cn'
timeZone = "Asia/Shanghai"
title = 'Elari的博客'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]
